# Site settings
title: Haeri Yoon
description: Digital Test Engineer at Analog Devices, Inc. 
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Haeri Yoon
user_description: I\'m a <b>Digital Test Engineer</b>, currently working at Analog Devices, Inc. 
user_title: Digital Test Engineer
email: celenay16@protonmail.com
# twitter_username: lorem_ipsum
github_username:  haeriy
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
